## Default profile
spring:
  application:
    name: CapStone
  profiles:
    active: dev
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    displayRequestDuration: true

---
# Local Profile
spring:
  config:
    activate:
      on-profile: local
  # H2
  h2:
    console:
      enabled: true
      path: ${H2_PATH}
      settings:
        web-allow-others: true
  datasource:
    url: ${H2_URL}
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  # KAKAO
  oauth:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      url:
        auth: https://kauth.kakao.com
        api: https://kapi.kakao.com
        map: https://dapi.kakao.com/v2/local/search/keyword.json
  virtual:
    password: ${KAKAO_PASSWORD}
  # Redis
  data:
    redis:
      host: localhost
      port: 6379
  # 네이버 메일
  email:
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}

---
# Dev Profile
spring:
  config:
    activate:
      on-profile: dev
  # H2
  h2:
    console:
      enabled: true
      path: ${H2_PATH}
      settings:
        web-allow-others: true
  datasource:
    url: ${H2_URL}
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  # KAKAO
  oauth:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      url:
        auth: https://kauth.kakao.com
        api: https://kapi.kakao.com
        map: https://dapi.kakao.com/v2/local/search/keyword.json
  virtual:
    password: ${SOCIAL_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  # 네이버 메일
  email:
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}

---
#jwt
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: ${JWT_ACCESS_TOKEN_TIME}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_TIME}
